import json, os

NOTEBOOKS_DIR = os.path.dirname(os.path.abspath(__file__))

def md(*lines):
    return {'cell_type': 'markdown', 'metadata': {}, 'source': list(lines)}

def code(*lines):
    return {'cell_type': 'code', 'execution_count': None, 'metadata': {},
            'outputs': [], 'source': list(lines)}

cells = [

md(
 '# Human Annotation Analysis\n',
 '\n',
 '## What this notebook does\n',
 'Seven human annotators evaluated **45 (target, source analogy) pairs** -- 15 target concepts, each with 3 candidate source analogies.\n',
 'Each annotator gave three independent scores (1-3) per pair, then ranked the 3 sources from best (rank 1) to worst (rank 3).\n',
 '\n',
 'This notebook answers four questions:\n',
 '1. **Which source analogy had the most and least agreement across annotators?**\n',
 '2. **How much do annotators agree overall?** (inter-annotator agreement)\n',
 '3. **Which rating dimension had the highest agreement?** (coherence vs. mapping vs. explanatory power)\n',
 '4. **Were annotations tightly clustered or all over the place?**\n',
 '\n',
 'It then cross-references the XLSX file to answer: **which LLMs generated the best and worst-rated analogies?**\n',
 '\n',
 '---\n',
 '### Scoring rubric (all dimensions use a 1-3 scale)\n',
 '| Score | Meaning |\n',
 '|-------|--------|\n',
 '| **3** | Strong / clearly works |\n',
 '| **2** | Partial / works with caveats |\n',
 '| **1** | Does not work / poor or misleading |\n',
 '\n',
 '**Coherence** -- Does the pairing click intuitively? No explanation needed = 3. Needs a sentence = 2. Forced or confusing = 1.\n',
 '\n',
 '**Mapping** -- Do the key parts of the target have clear counterparts in the source? All key parts map = 3. Most = 2. Few or none = 1.\n',
 '\n',
 '**Explanatory Power** -- Would a learner gain real understanding from this analogy? Builds full understanding = 3. Teaches some things well = 2. Vague or misleading = 1.\n',
 '\n',
 '**Rank** -- After rating, annotators ranked the 3 sources: 1 = best, 3 = worst.\n',
),

code(
 '# CELL 1 -- Imports & helpers\n',
 'import glob, os, warnings\n',
 'import numpy as np\n',
 'import pandas as pd\n',
 'import matplotlib.pyplot as plt\n',
 'import matplotlib.patches as mpatches\n',
 'import seaborn as sns\n',
 'from scipy import stats\n',
 '\n',
 'warnings.filterwarnings("ignore")\n',
 'plt.rcParams.update({"font.size": 10, "axes.titlesize": 12,\n',
 '                     "axes.titleweight": "bold", "figure.dpi": 120})\n',
 '\n',
 'STEEL  = "#4682B4"\n',
 'CORAL  = "#FF7F50"\n',
 'GRAY   = "#9E9E9E"\n',
 'GREEN  = "#5BA85B"\n',
 'AMBER  = "#E8A838"\n',
 '\n',
 'DIMS       = ["coherence", "mapping", "explanatory"]\n',
 'DIM_LABELS = ["Coherence", "Mapping", "Explanatory Power"]\n',
 'DIM_COLORS = [STEEL, AMBER, CORAL]\n',
 '\n',
 'try:\n',
 '    import krippendorff\n',
 '    def _kripp_alpha(matrix):\n',
 '        return krippendorff.alpha(matrix, level_of_measurement="ordinal")\n',
 '    print("krippendorff package found.")\n',
 'except ImportError:\n',
 '    print("krippendorff not installed -- run:  pip install krippendorff")\n',
 '    def _kripp_alpha(data):\n',
 '        """Manual Krippendorff ordinal alpha fallback."""\n',
 '        data = np.array(data, dtype=float)\n',
 '        vals = np.unique(data[~np.isnan(data)])\n',
 '        flat = data[~np.isnan(data)]\n',
 '        n    = len(flat)\n',
 '        def ord_diff(v1, v2):\n',
 '            if v1 == v2: return 0.0\n',
 '            lo, hi = sorted([v1, v2])\n',
 '            lo_i = np.searchsorted(vals, lo)\n',
 '            hi_i = np.searchsorted(vals, hi)\n',
 '            s = 0.0\n',
 '            for k in range(lo_i, hi_i):\n',
 '                g_k  = np.sum(flat <= vals[k])   / n\n',
 '                g_k1 = np.sum(flat <= vals[k+1]) / n\n',
 '                s += ((g_k + g_k1) / 2 - lo_i / len(vals)) ** 2\n',
 '            return s\n',
 '        _, n_items = data.shape\n',
 '        D_o, pairs_o = 0.0, 0\n',
 '        for j in range(n_items):\n',
 '            col = data[:, j]; col = col[~np.isnan(col)]\n',
 '            for u in range(len(col)):\n',
 '                for v in range(u+1, len(col)):\n',
 '                    D_o += ord_diff(col[u], col[v]); pairs_o += 1\n',
 '        D_o /= max(pairs_o, 1)\n',
 '        D_e, cnt = 0.0, 0\n',
 '        for u in range(n):\n',
 '            for v in range(u+1, n):\n',
 '                D_e += ord_diff(flat[u], flat[v]); cnt += 1\n',
 '        D_e /= max(cnt, 1)\n',
 '        return 1 - D_o / D_e if D_e else 1.0\n',
 '\n',
 '\n',
 'def kendall_w(rank_matrix):\n',
 '    """Kendall W for a (n_raters x n_items) matrix. Returns 0-1."""\n',
 '    m, n = rank_matrix.shape\n',
 '    rs   = rank_matrix.sum(axis=0)\n',
 '    S    = np.sum((rs - rs.mean()) ** 2)\n',
 '    return 12 * S / (m**2 * (n**3 - n))\n',
 '\n',
 '\n',
 'def interp(v):\n',
 '    if v >= 0.80: return "Strong"\n',
 '    if v >= 0.60: return "Moderate"\n',
 '    if v >= 0.40: return "Fair"\n',
 '    return "Poor"\n',
 '\n',
 'print("Setup complete.")',
),

code(
 '# CELL 2 -- Load human annotation CSVs\n',
 'RESULTS_DIR = os.path.join(\n',
 '    os.path.dirname(os.path.abspath("__file__")),\n',
 '    "..", "human_annotation", "human_results"\n',
 ')\n',
 'csv_files = glob.glob(os.path.join(RESULTS_DIR, "*.csv"))\n',
 'print(f"Found {len(csv_files)} annotator files")\n',
 '\n',
 'df = pd.concat([pd.read_csv(f) for f in csv_files], ignore_index=True)\n',
 'df.columns = df.columns.str.strip().str.lower()\n',
 'df["target"]         = df["target"].str.strip()\n',
 'df["source_analogy"] = df["source_analogy"].str.strip()\n',
 'df["overall"]        = df[DIMS].mean(axis=1)\n',
 'df["item_key"]       = df["target"] + " || " + df["source_analogy"]\n',
 '\n',
 'ANNOTATORS = sorted(df["annotator_id"].unique())\n',
 'ITEMS      = sorted(df["item_key"].unique())\n',
 'TARGETS    = sorted(df["target"].unique())\n',
 '\n',
 'print(f"Annotators : {len(ANNOTATORS)}")\n',
 'print(f"Targets    : {len(TARGETS)}")\n',
 'print(f"Item pairs : {len(ITEMS)}")\n',
 'print(f"Total rows : {len(df)}")\n',
 "print(f\"Missing    : {df[DIMS + ['rank']].isna().sum().to_dict()}\")",
),

md(
 '---\n',
 '## 1. Inter-Annotator Agreement\n',
 '\n',
 "### What is Krippendorff's alpha?\n",
 "Krippendorff's alpha is a **reliability coefficient** that measures how consistently multiple raters assign\n",
 'scores to the same items. It accounts for the **ordinal scale** (numbers 1, 2, 3 have order but equal spacing\n',
 'is not assumed), the number of raters and items, and removes random-chance agreement\n',
 '(alpha = 0 means no better than chance).\n',
 '\n',
 '**Range:** -1 (systematic disagreement) -> 0 (chance) -> 1 (perfect agreement).\n',
 '**Rule of thumb:** alpha >= 0.8 = reliable; 0.6-0.8 = tentatively reliable; < 0.6 = not reliable.\n',
 '\n',
 "### What is Kendall's W?\n",
 "Kendall's W measures **agreement on rankings** across raters. Here: how consistently 7 annotators ranked\n",
 'the 3 source analogies for each target from best (1) to worst (3).\n',
 '\n',
 '**Range:** 0 (random) -> 1 (all raters ranked identically).\n',
 '**Rule of thumb:** W >= 0.7 = strong agreement on ordering.\n',
),

code(
 '# CELL 3 -- Compute IAA metrics\n',
 'def reliability_matrix(col):\n',
 '    piv = df.pivot_table(index="annotator_id", columns="item_key",\n',
 '                         values=col, aggfunc="first")\n',
 '    return piv.reindex(index=ANNOTATORS, columns=ITEMS).values.astype(float)\n',
 '\n',
 'alphas = {d: _kripp_alpha(reliability_matrix(d)) for d in DIMS}\n',
 '\n',
 'w_by_target = {}\n',
 'for target, grp in df.groupby("target"):\n',
 '    piv = grp.pivot_table(index="annotator_id", columns="source_analogy",\n',
 '                          values="rank", aggfunc="first")\n',
 '    piv = piv.reindex(index=ANNOTATORS).dropna()\n',
 '    if piv.shape[0] >= 2 and piv.shape[1] >= 2:\n',
 '        w_by_target[target] = kendall_w(piv.values.astype(float))\n',
 'mean_w = np.mean(list(w_by_target.values()))\n',
 '\n',
 'iaa = pd.DataFrame([\n',
 '    {"Metric": "Krippendorff alpha (ordinal)", "Scope": "Coherence scores",\n',
 '     "Value": alphas["coherence"],   "Interpretation": interp(alphas["coherence"])},\n',
 '    {"Metric": "Krippendorff alpha (ordinal)", "Scope": "Mapping scores",\n',
 '     "Value": alphas["mapping"],     "Interpretation": interp(alphas["mapping"])},\n',
 '    {"Metric": "Krippendorff alpha (ordinal)", "Scope": "Explanatory Power scores",\n',
 '     "Value": alphas["explanatory"], "Interpretation": interp(alphas["explanatory"])},\n',
 '    {"Metric": "Kendall W", "Scope": "Rankings (avg over 15 targets)",\n',
 '     "Value": mean_w, "Interpretation": interp(mean_w)},\n',
 '])\n',
 'iaa["Value"] = iaa["Value"].round(3)\n',
 'print(iaa.to_string(index=False))\n',
 'best_dim = max(alphas, key=alphas.get)\n',
 'print(f"\\n-> Highest agreement dimension: {best_dim}  (alpha = {alphas[best_dim]:.3f})")\n',
 'print(f"-> Mean ranking agreement W: {mean_w:.3f} -- {interp(mean_w)}")',
),

code(
 '# CELL 4 -- Figure: alpha by dimension + Kendall W per target\n',
 'fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n',
 '\n',
 'ax = axes[0]\n',
 'dim_vals = [alphas[d] for d in DIMS]\n',
 'bars = ax.bar(DIM_LABELS, dim_vals, color=DIM_COLORS, edgecolor="white", width=0.55)\n',
 'ax.axhline(0.8, color="black", ls="--", lw=1.2, label="Reliable threshold (0.8)")\n',
 'ax.axhline(0.6, color=GRAY,   ls=":",  lw=1.0, label="Tentative threshold (0.6)")\n',
 'ax.set_ylim(0, 1.05)\n',
 "ax.set_ylabel(\"Krippendorff's alpha\", fontsize=11)\n",
 'ax.set_title("Inter-Annotator Agreement\\nby Rating Dimension")\n',
 'ax.legend(fontsize=8)\n',
 'for bar, v in zip(bars, dim_vals):\n',
 '    ax.text(bar.get_x() + bar.get_width()/2, v + 0.015,\n',
 '            f"{v:.3f}\\n({interp(v)})", ha="center", va="bottom", fontsize=8.5)\n',
 '\n',
 'ax = axes[1]\n',
 'ws = pd.Series(w_by_target).sort_values(ascending=True)\n',
 'bar_colors = [STEEL if v >= 0.6 else CORAL if v < 0.4 else AMBER for v in ws]\n',
 'ax.barh(ws.index, ws.values, color=bar_colors, edgecolor="white", height=0.65)\n',
 'ax.axvline(mean_w, color="black", lw=1.4, ls="--", label=f"Mean W = {mean_w:.3f}")\n',
 'ax.set_xlim(0, 1)\n',
 "ax.set_xlabel(\"Kendall's W (0=random, 1=identical rankings)\", fontsize=10)\n",
 'ax.set_title("Ranking Agreement per Target")\n',
 'for y, (target, v) in enumerate(ws.items()):\n',
 '    ax.text(v + 0.01, y, f"{v:.2f}", va="center", fontsize=8)\n',
 'strong = mpatches.Patch(color=STEEL, label="W >= 0.6 (strong)")\n',
 'mid    = mpatches.Patch(color=AMBER, label="0.4-0.6 (moderate)")\n',
 'weak   = mpatches.Patch(color=CORAL, label="W < 0.4 (weak)")\n',
 'ax.legend(handles=[strong, mid, weak], fontsize=8, loc="lower right")\n',
 '\n',
 'plt.tight_layout()\n',
 'os.makedirs("../results/human_annotation", exist_ok=True)\n',
 'plt.savefig("../results/human_annotation/iaa_overview.pdf", bbox_inches="tight")\n',
 'plt.savefig("../results/human_annotation/iaa_overview.png", dpi=150, bbox_inches="tight")\n',
 'plt.show()',
),

md(
 '---\n',
 '## 2. Source-Level Agreement: Which Analogy Had Most / Least Consensus?\n',
 '\n',
 'For each of the 45 (target, source) pairs we compute the **standard deviation (SD) of scores\n',
 'across the 7 annotators** for every dimension.\n',
 '\n',
 '- **SD = 0** -- all 7 annotators gave the exact same score (perfect consensus).\n',
 '- **SD near 1** -- annotators spread across all three score values (maximum disagreement on a 1-3 scale).\n',
 '\n',
 'We rank pairs by **mean SD** (average over the three dimensions) to find the most\n',
 'and least agreed-upon analogies.\n',
),

code(
 '# CELL 5 -- Source-level agreement (SD per item)\n',
 'item_stats = df.groupby(["target", "source_analogy"]).agg(\n',
 '    coh_mean  = ("coherence",   "mean"),\n',
 '    coh_std   = ("coherence",   "std"),\n',
 '    map_mean  = ("mapping",     "mean"),\n',
 '    map_std   = ("mapping",     "std"),\n',
 '    exp_mean  = ("explanatory", "mean"),\n',
 '    exp_std   = ("explanatory", "std"),\n',
 '    overall   = ("overall",     "mean"),\n',
 '    maj_rank  = ("rank", lambda s: s.mode().iloc[0]),\n',
 '    rank_std  = ("rank", "std"),\n',
 ').reset_index()\n',
 'item_stats["mean_sd"] = item_stats[["coh_std","map_std","exp_std"]].mean(axis=1)\n',
 '\n',
 'top_agree    = item_stats.nsmallest(5, "mean_sd")\n',
 'top_disagree = item_stats.nlargest(5, "mean_sd")\n',
 '\n',
 'print("TOP 5 -- Highest annotator consensus (lowest mean SD):")\n',
 'print(top_agree[["target","source_analogy","overall","mean_sd",\n',
 '                  "coh_std","map_std","exp_std"]].round(3).to_string(index=False))\n',
 'print()\n',
 'print("TOP 5 -- Least consensus (highest mean SD):")\n',
 'print(top_disagree[["target","source_analogy","overall","mean_sd",\n',
 '                     "coh_std","map_std","exp_std"]].round(3).to_string(index=False))',
),

code(
 '# CELL 6 -- Figure: SD distribution + sorted bar per analogy\n',
 'fig, axes = plt.subplots(1, 2, figsize=(13, 5))\n',
 '\n',
 'ax = axes[0]\n',
 'ax.hist(item_stats["mean_sd"], bins=14, color=STEEL, edgecolor="white", alpha=0.85)\n',
 'mean_sd_val = item_stats["mean_sd"].mean()\n',
 'ax.axvline(mean_sd_val, color="black", lw=1.5, ls="--",\n',
 '           label=f"Mean SD = {mean_sd_val:.2f}")\n',
 'ax.set_xlabel("Mean SD across annotators (lower = more agreement)", fontsize=10)\n',
 'ax.set_ylabel("Number of (target, source) pairs", fontsize=10)\n',
 'ax.set_title("How Spread Out Were the Scores?\\n(all 45 pairs)")\n',
 'ax.legend(fontsize=9)\n',
 'n_tight = (item_stats["mean_sd"] < 0.4).sum()\n',
 'n_mid   = ((item_stats["mean_sd"] >= 0.4) & (item_stats["mean_sd"] < 0.8)).sum()\n',
 'n_wide  = (item_stats["mean_sd"] >= 0.8).sum()\n',
 'ax.text(0.55, ax.get_ylim()[1]*0.88,\n',
 '        f"Tight (<0.4): {n_tight}\\nModerate (0.4-0.8): {n_mid}\\nWide (>=0.8): {n_wide}",\n',
 '        fontsize=8.5, va="top",\n',
 '        bbox=dict(boxstyle="round,pad=0.3", facecolor="white", alpha=0.7))\n',
 '\n',
 'ax = axes[1]\n',
 'sorted_items = item_stats.sort_values("mean_sd", ascending=False)\n',
 'y = np.arange(len(sorted_items))\n',
 'dot_colors = [CORAL if v >= 0.8 else AMBER if v >= 0.4 else GREEN\n',
 '              for v in sorted_items["mean_sd"]]\n',
 'ax.barh(y, sorted_items["mean_sd"], color=dot_colors, edgecolor="white", height=0.7)\n',
 'ax.axvline(mean_sd_val, color="black", lw=1.2, ls="--")\n',
 'ax.set_yticks(y)\n',
 "ax.set_yticklabels(\n",
 "    [f\"{row['source_analogy'][:22]} ({row['target'][:14]})\"\n",
 "     for _, row in sorted_items.iterrows()],\n",
 '    fontsize=7)\n',
 'ax.set_xlabel("Mean SD across annotators", fontsize=10)\n',
 'ax.set_title("Agreement per Source Analogy\\n(most disagreement at top)")\n',
 'ax.set_xlim(0, 1.1)\n',
 'tight_p = mpatches.Patch(color=GREEN, label="Tight (<0.4)")\n',
 'mod_p   = mpatches.Patch(color=AMBER, label="Moderate (0.4-0.8)")\n',
 'wide_p  = mpatches.Patch(color=CORAL, label="Wide (>=0.8)")\n',
 'ax.legend(handles=[tight_p, mod_p, wide_p], fontsize=8, loc="lower right")\n',
 '\n',
 'plt.tight_layout()\n',
 'plt.savefig("../results/human_annotation/source_agreement.pdf", bbox_inches="tight")\n',
 'plt.savefig("../results/human_annotation/source_agreement.png", dpi=150, bbox_inches="tight")\n',
 'plt.show()',
),

md(
 '---\n',
 '## 3. Were Annotations Close or All Over the Place?\n',
 '\n',
 'We classify each (pair, dimension) combination by its **spread type**:\n',
 '- **Unanimous** -- all 7 annotators gave the same score (difference = 0)\n',
 '- **+/-1 spread** -- max difference between any two annotators is 1 point\n',
 '- **Wide spread** -- at least one annotator differed by 2 points (e.g. someone gave 1, someone gave 3)\n',
 '\n',
 'A high unanimous rate means the task was clear and analogies were unambiguous.\n',
 'Wide spread means annotators genuinely disagreed -- either the analogy is ambiguous,\n',
 'or the dimension is harder to judge.\n',
 '\n',
 'The **Score vs SD scatter** shows each dot as one (target, source) pair.\n',
 'Bottom-left = low score AND low spread (bad analogies everyone agrees are bad).\n',
 'Top-right = high score AND high spread (good analogies that are contested).\n',
),

code(
 '# CELL 7 -- Score spread analysis\n',
 'consensus_rows = []\n',
 'for item, grp in df.groupby("item_key"):\n',
 '    for dim in DIMS:\n',
 '        vals = grp[dim].dropna().values\n',
 '        rng  = vals.max() - vals.min()\n',
 '        if rng == 0:   label = "Unanimous"\n',
 '        elif rng <= 1: label = "+/-1 spread"\n',
 '        else:          label = "Wide spread"\n',
 '        consensus_rows.append({"item": item, "dimension": dim,\n',
 '                                "spread_type": label, "std": vals.std()})\n',
 'cons_df = pd.DataFrame(consensus_rows)\n',
 '\n',
 'total = len(cons_df)\n',
 'print("Spread breakdown (45 pairs x 3 dimensions = 135 combinations):")\n',
 'for label in ["Unanimous", "+/-1 spread", "Wide spread"]:\n',
 '    n = (cons_df["spread_type"] == label).sum()\n',
 '    print(f"  {label:15s}: {n:3d} / {total}  ({n/total:.0%})")\n',
 'print()\n',
 'print("By dimension:")\n',
 'print(cons_df.groupby(["dimension","spread_type"]).size().unstack(fill_value=0))',
),

code(
 '# CELL 8 -- Figures: spread breakdown + score vs SD scatter\n',
 'fig, axes = plt.subplots(1, 3, figsize=(14, 4.5))\n',
 'spread_types  = ["Unanimous", "+/-1 spread", "Wide spread"]\n',
 'spread_colors = [STEEL, AMBER, CORAL]\n',
 'for ax, dim, label in zip(axes, DIMS, DIM_LABELS):\n',
 '    sub = cons_df[cons_df["dimension"] == dim]\n',
 '    counts = [sub[sub["spread_type"] == t].shape[0] for t in spread_types]\n',
 '    bars = ax.bar(spread_types, counts, color=spread_colors, edgecolor="white")\n',
 '    ax.set_title(f"{label}\\n(n=45 pairs)")\n',
 '    ax.set_ylabel("Number of pairs")\n',
 '    ax.set_ylim(0, 50)\n',
 '    for bar, c in zip(bars, counts):\n',
 '        ax.text(bar.get_x() + bar.get_width()/2, c + 0.5,\n',
 '                f"{c} ({c/45:.0%})", ha="center", va="bottom", fontsize=8.5)\n',
 '    ax.tick_params(axis="x", labelsize=8)\n',
 'plt.suptitle("Score Spread Type Across All (Target, Source) Pairs",\n',
 '             fontsize=10, y=1.03)\n',
 'plt.tight_layout()\n',
 'plt.savefig("../results/human_annotation/spread_breakdown.pdf", bbox_inches="tight")\n',
 'plt.savefig("../results/human_annotation/spread_breakdown.png", dpi=150, bbox_inches="tight")\n',
 'plt.show()\n',
 '\n',
 '# Score vs SD scatter\n',
 'fig, axes = plt.subplots(1, 3, figsize=(14, 4.5), sharey=True)\n',
 'std_cols  = ["coh_std",  "map_std",  "exp_std"]\n',
 'mean_cols = ["coh_mean", "map_mean", "exp_mean"]\n',
 'for ax, std_col, mean_col, label in zip(axes, std_cols, mean_cols, DIM_LABELS):\n',
 '    colors_dot = [{1: STEEL, 2: AMBER, 3: CORAL}[int(r)] for r in item_stats["maj_rank"]]\n',
 '    ax.scatter(item_stats[mean_col], item_stats[std_col],\n',
 '               c=colors_dot, s=80, alpha=0.8, edgecolors="white", linewidths=0.6)\n',
 '    ax.set_xlabel(f"Mean {label} Score", fontsize=10)\n',
 '    ax.set_title(f"{label}")\n',
 '    ax.set_xlim(0.7, 3.3)\n',
 '    ax.set_ylim(-0.05, 1.3)\n',
 '    ax.set_xticks([1, 2, 3])\n',
 'axes[0].set_ylabel("SD across annotators (0=all same, higher=more disagreement)", fontsize=9)\n',
 'r1 = mpatches.Patch(color=STEEL, label="Majority rank 1 (best)")\n',
 'r2 = mpatches.Patch(color=AMBER, label="Majority rank 2")\n',
 'r3 = mpatches.Patch(color=CORAL, label="Majority rank 3 (worst)")\n',
 'axes[1].legend(handles=[r1, r2, r3], fontsize=8, loc="upper left")\n',
 'plt.suptitle("Mean Score vs Annotator Disagreement -- each dot = one (target, source) pair",\n',
 '             fontsize=10, y=1.02)\n',
 'plt.tight_layout()\n',
 'plt.savefig("../results/human_annotation/score_vs_spread.pdf", bbox_inches="tight")\n',
 'plt.savefig("../results/human_annotation/score_vs_spread.png", dpi=150, bbox_inches="tight")\n',
 'plt.show()',
),

md(
 '---\n',
 '## 4. LLM Attribution: Which Models Generated the Best and Worst Analogies?\n',
 '\n',
 'The XLSX file records for each of the 45 pairs:\n',
 '- **Model** -- which LLM generated the analogy (e.g. gpt-oss-120b, grok-4-fast, qwen3-14b, ...)\n',
 '- **Mode** -- `targetonly` (only the target name given) vs. `withsub` (target + subconcepts given)\n',
 '- **Analogy Type** -- how the analogy was selected: `baseline`, `embedding`, or `rerank`\n',
 '- **Quality Tier** -- HIGH / MIDDLE / LOW, assigned based on LLM judge consensus scores\n',
 '\n',
 'We join these to the human scores to see:\n',
 '1. Do the LLM judge Quality Tiers match what human annotators thought?\n',
 '2. Which models generated the highest human-rated analogies?\n',
 '3. Full ranking of all 45 analogies by human score.\n',
),

code(
 '# CELL 9 -- Load XLSX\n',
 'XLSX_PATH = os.path.join(\n',
 '    os.path.dirname(os.path.abspath("__file__")),\n',
 '    "..", "human_annotation", "15_targets_full_data_with_reasoning.xlsx"\n',
 ')\n',
 'raw = pd.read_excel(XLSX_PATH, header=None)\n',
 '# Row 1 contains actual column names; data starts at row 2\n',
 'sub_row = raw.iloc[1]\n',
 'xlsx = raw.iloc[2:].copy()\n',
 'xlsx.columns = [str(c).strip() if pd.notna(c) else f"col_{i}"\n',
 '                for i, c in enumerate(sub_row)]\n',
 'xlsx = xlsx.reset_index(drop=True)\n',
 '\n',
 'keep = ["#", "Agreement File", "Target", "Domain", "Quality Tier",\n',
 '        "Analogy", "Model", "Mode", "Analogy Type", "Consensus"]\n',
 'xlsx = xlsx[[c for c in keep if c in xlsx.columns]].copy()\n',
 'xlsx["Target"] = xlsx["Target"].ffill().str.strip()\n',
 'if "Domain" in xlsx.columns:\n',
 '    xlsx["Domain"] = xlsx["Domain"].ffill().str.strip()\n',
 'xlsx = xlsx.dropna(subset=["Analogy"])\n',
 'xlsx["Analogy"]   = xlsx["Analogy"].str.strip()\n',
 'xlsx["Consensus"] = pd.to_numeric(xlsx["Consensus"], errors="coerce")\n',
 '\n',
 'print("XLSX rows:", len(xlsx))\n',
 'print(xlsx[["Target","Quality Tier","Analogy","Model","Mode"]].head(9).to_string(index=False))',
),

code(
 '# CELL 10 -- Join human scores into XLSX table\n',
 'xlsx["_tgt"] = xlsx["Target"].str.lower()\n',
 'xlsx["_ana"] = xlsx["Analogy"].str.lower()\n',
 'item_stats["_tgt"] = item_stats["target"].str.lower()\n',
 'item_stats["_ana"] = item_stats["source_analogy"].str.lower()\n',
 '\n',
 'enriched = pd.merge(xlsx, item_stats, on=["_tgt","_ana"], how="left")\n',
 'print(f"Matched {enriched[\'overall\'].notna().sum()} / {len(enriched)} rows to human scores")\n',
 '\n',
 'cols_show = ["Target","Domain","Quality Tier","Analogy","Model","Mode",\n',
 '             "overall","coh_mean","map_mean","exp_mean","mean_sd","Consensus"]\n',
 'print(enriched[[c for c in cols_show if c in enriched.columns]].round(3).to_string(index=False))',
),

code(
 '# CELL 11 -- Figure: Human scores by Quality Tier\n',
 'tier_order  = ["HIGH", "MIDDLE", "LOW"]\n',
 'tier_colors = [STEEL, AMBER, CORAL]\n',
 '\n',
 'fig, axes = plt.subplots(1, 2, figsize=(12, 5))\n',
 '\n',
 'ax = axes[0]\n',
 'tier_means = enriched.groupby("Quality Tier")["overall"].agg(["mean","std"]).reindex(tier_order)\n',
 'bars = ax.bar(["HIGH tier", "MIDDLE tier", "LOW tier"],\n',
 '              tier_means["mean"], yerr=tier_means["std"],\n',
 '              color=tier_colors, edgecolor="white",\n',
 '              error_kw=dict(elinewidth=1.2, capsize=4))\n',
 'ax.set_ylim(0, 3.5); ax.set_yticks([1, 2, 3])\n',
 'ax.set_ylabel("Mean Human Overall Score (1-3)", fontsize=10)\n',
 'ax.set_title("Human Scores by Quality Tier\\n(error bars = SD across analogies in tier)")\n',
 'for bar, (_, row) in zip(bars, tier_means.iterrows()):\n',
 "    ax.text(bar.get_x() + bar.get_width()/2,\n",
 "            row['mean'] + row['std'] + 0.05,\n",
 "            f\"{row['mean']:.2f}\", ha='center', fontsize=9)\n",
 'ax.axhline(2, color="gray", lw=0.8, ls=":")\n',
 '\n',
 'ax = axes[1]\n',
 'melted = enriched[enriched["Quality Tier"].isin(tier_order)].copy()\n',
 'melted = melted.melt(id_vars="Quality Tier",\n',
 '                     value_vars=["coh_mean","map_mean","exp_mean"],\n',
 '                     var_name="Dimension", value_name="Score")\n',
 'melted["Dimension"] = melted["Dimension"].map(\n',
 '    {"coh_mean": "Coherence", "map_mean": "Mapping", "exp_mean": "Explanatory"})\n',
 'sns.boxplot(data=melted, x="Dimension", y="Score", hue="Quality Tier",\n',
 '            hue_order=tier_order,\n',
 '            palette={"HIGH": STEEL, "MIDDLE": AMBER, "LOW": CORAL},\n',
 '            ax=ax, width=0.55)\n',
 'ax.set_ylim(0.5, 3.5); ax.set_yticks([1, 2, 3])\n',
 'ax.set_title("Score Distribution by Tier and Dimension")\n',
 'ax.legend(title="Quality Tier", fontsize=8)\n',
 '\n',
 'plt.tight_layout()\n',
 'plt.savefig("../results/human_annotation/tier_vs_human.pdf", bbox_inches="tight")\n',
 'plt.savefig("../results/human_annotation/tier_vs_human.png", dpi=150, bbox_inches="tight")\n',
 'plt.show()\n',
 '\n',
 'sub = enriched[["Consensus","overall"]].dropna()\n',
 'if len(sub) > 3:\n',
 '    r, p = stats.spearmanr(sub["Consensus"], sub["overall"])\n',
 '    print(f"\\nSpearman r (LLM consensus vs human overall): r={r:.3f}, p={p:.4f}")',
),

code(
 '# CELL 12 -- Model performance table\n',
 'model_scores = enriched.groupby("Model").agg(\n',
 '    n_analogies   = ("overall", "count"),\n',
 '    human_overall = ("overall", "mean"),\n',
 '    llm_consensus = ("Consensus", "mean"),\n',
 '    n_high   = ("Quality Tier", lambda s: (s == "HIGH").sum()),\n',
 '    n_middle = ("Quality Tier", lambda s: (s == "MIDDLE").sum()),\n',
 '    n_low    = ("Quality Tier", lambda s: (s == "LOW").sum()),\n',
 ').reset_index().sort_values("human_overall", ascending=False)\n',
 '\n',
 'print("Model performance (sorted by mean human overall score):")\n',
 'print(model_scores.round(3).to_string(index=False))',
),

code(
 '# CELL 13 -- Figure: model ranking + tier distribution\n',
 'fig, axes = plt.subplots(1, 2, figsize=(14, max(4, len(model_scores) * 0.5)))\n',
 '\n',
 'ax = axes[0]\n',
 'ms = model_scores.sort_values("human_overall", ascending=True)\n',
 'bar_c = [STEEL if v >= 2.5 else AMBER if v >= 2.0 else CORAL for v in ms["human_overall"]]\n',
 'ax.barh(ms["Model"], ms["human_overall"], color=bar_c, edgecolor="white", height=0.65)\n',
 'mean_human = ms["human_overall"].mean()\n',
 'ax.axvline(mean_human, color="black", lw=1.2, ls="--", label=f"Mean = {mean_human:.2f}")\n',
 'ax.set_xlabel("Mean Human Overall Score", fontsize=10)\n',
 'ax.set_title("Model Ranking by Human Evaluation Score")\n',
 'ax.set_xlim(0, 3.3); ax.set_xticks([1, 1.5, 2, 2.5, 3])\n',
 'for y, (_, row) in enumerate(ms.iterrows()):\n',
 "    ax.text(row['human_overall'] + 0.03, y,\n",
 "            f\"{row['human_overall']:.2f}\", va='center', fontsize=8)\n",
 'ax.legend(fontsize=9)\n',
 '\n',
 'ax = axes[1]\n',
 'y = np.arange(len(ms))\n',
 'ax.barh(y, ms["n_high"],   color=STEEL, edgecolor="white", height=0.65, label="HIGH tier")\n',
 'ax.barh(y, ms["n_middle"], color=AMBER, edgecolor="white", height=0.65,\n',
 '        left=ms["n_high"], label="MIDDLE tier")\n',
 'ax.barh(y, ms["n_low"],    color=CORAL, edgecolor="white", height=0.65,\n',
 '        left=ms["n_high"] + ms["n_middle"], label="LOW tier")\n',
 'ax.set_yticks(y); ax.set_yticklabels(ms["Model"], fontsize=8.5)\n',
 'ax.set_xlabel("Number of analogies generated", fontsize=10)\n',
 'ax.set_title("Quality Tier Distribution per Model")\n',
 'ax.legend(fontsize=9)\n',
 '\n',
 'plt.tight_layout()\n',
 'plt.savefig("../results/human_annotation/model_scores.pdf", bbox_inches="tight")\n',
 'plt.savefig("../results/human_annotation/model_scores.png", dpi=150, bbox_inches="tight")\n',
 'plt.show()',
),

code(
 '# CELL 14 -- Full ranking: all 45 analogies sorted by human score\n',
 'ordered = enriched[["Target","Domain","Quality Tier","Analogy","Model","Mode",\n',
 '                     "overall","coh_mean","map_mean","exp_mean","mean_sd","Consensus"]].copy()\n',
 'ordered = ordered.sort_values("overall", ascending=False).reset_index(drop=True)\n',
 'ordered.index += 1\n',
 'ordered.columns = ["Target","Domain","Tier","Analogy","Model","Mode",\n',
 '                    "Human","Coh","Map","Exp","SD","LLM_Consensus"]\n',
 'ordered = ordered.round(3)\n',
 'print("All 45 analogies ranked by mean human overall score (rank 1 = best):")\n',
 'print(ordered.to_string())\n',
 'print("\\n" + "="*55)\n',
 'print("TOP 5:")\n',
 'print(ordered.head(5)[["Target","Tier","Analogy","Model","Human","SD"]].to_string())\n',
 'print("\\nBOTTOM 5:")\n',
 'print(ordered.tail(5)[["Target","Tier","Analogy","Model","Human","SD"]].to_string())',
),

code(
 '# CELL 15 -- Summary numbers for thesis\n',
 'pct_unan = (cons_df["spread_type"] == "Unanimous").sum()   / len(cons_df)\n',
 'pct_pm1  = (cons_df["spread_type"] == "+/-1 spread").sum() / len(cons_df)\n',
 'pct_wide = (cons_df["spread_type"] == "Wide spread").sum() / len(cons_df)\n',
 'best_model  = model_scores.iloc[0]["Model"]  if len(model_scores) else "N/A"\n',
 'worst_model = model_scores.iloc[-1]["Model"] if len(model_scores) else "N/A"\n',
 '\n',
 'print("="*65)\n',
 'print("KEY NUMBERS FOR THESIS\\n")\n',
 'print("Annotators  : 7")\n',
 'print("Item pairs  : 45  (15 targets x 3 sources)")\n',
 'print(f"Total rows  : {len(df)}")\n',
 'print()\n',
 'print("Inter-annotator agreement:")\n',
 'for d, lab in zip(DIMS, DIM_LABELS):\n',
 '    print(f"  {lab:20s}: alpha = {alphas[d]:.3f}  ({interp(alphas[d])})")\n',
 'print(f"  Ranking (Kendall W)   : W = {mean_w:.3f}  ({interp(mean_w)})")\n',
 'print()\n',
 'print("Score spread:")\n',
 'print(f"  Unanimous      : {pct_unan:.0%}")\n',
 'print(f"  +/-1 spread    : {pct_pm1:.0%}")\n',
 'print(f"  Wide spread    : {pct_wide:.0%}")\n',
 'print()\n',
 'print("Model attribution:")\n',
 "print(f\"  Best  model: {best_model}  = {model_scores.iloc[0]['human_overall']:.2f}\")\n",
 "print(f\"  Worst model: {worst_model} = {model_scores.iloc[-1]['human_overall']:.2f}\")\n",
 'print("\\nFigures saved to ../results/human_annotation/")\n',
 'print("="*65)',
),

]

nb = {
    'cells': cells,
    'metadata': {
        'kernelspec': {
            'display_name': 'Python 3',
            'language': 'python',
            'name': 'python3'
        },
        'language_info': {
            'name': 'python',
            'version': '3.10.0'
        }
    },
    'nbformat': 4,
    'nbformat_minor': 5
}

out_path = os.path.join(NOTEBOOKS_DIR, 'human_annotation_analysis.ipynb')
with open(out_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

# Validate JSON roundtrip
with open(out_path, encoding='utf-8') as f:
    json.load(f)
print('Written and validated OK:', out_path)
